language: python
dist: xenial
python:
- '3.6'
#- '2.7'
#- '3.7'
os:
- linux
- osx
script:
- make wheel
deploy:
  provider: pypi
  user: mastak
  password:
    secure: YxxXCyPAxVkv7IZd1MvH5Dc+XpshmCFKiklM/xJ5sbblvTpvlIn0PV6W+Nvbf6O9zzePQ/MS9qzaBOtUe7ZOjkyB1PT/Td22KopjY9et1l28upyNEwEGqfRWpB/GK5pVcNHH5Opv6ert3utNQsU7I3WUhUUFzYQF5MGQTvtprODub81PI43aSnk9QtIyFb/8O9vOB31LmbEMeBcZXOkBti7yN45q7PBE7dwSIs4R+RMp07rJtukiUfj9cqk6K+LOrpmXbbQ34VlZLfSoioI0/0nF5x0RINI2QSgELSjHkh2Y1MgYzXA1EAe0YFtCSRjSbcDX1lTuWi0FnXf/fW5iERZuxCJsoXurkocWXkNPrv+VnVab2oNeLXWLt79vlMw+ihbZGdIAzwfBTQDMhvzcTSHXuCEfSl1oecw1KnG8MH6qD7CQ/Vzn9X9/X18bD2oacPalF9QKAV8H4JMiwprEadUZ5RhSawhUFE+g9mnntRWaAFJbjIZRkLoJVO03LP57RRGuBntybZrJeRt0B+9MEeS89toA3mw24BciJ125VfQX1TflLI6y7zk/erKxArjq/x3ncL60UNLHXEyIcFeo1pIqc85e+d1EBGhSaVKJylj0LMuqpJ2iFJA8ygfFACFfZ/34lMHx0ZDTSuyakLIyZuFhvOHq01Kar8Z/SeWD+2c=
  distributions: bdist_wheel
  skip_cleanup: true
  on:
    branch: master
  skip_existing: true
