language: python

os:
  - linux
#  - osx

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -r requirements.txt

script:
  - |
    cat <<EOF > setup.cfg
    [bdist_wheel]
    universal = false
    plat-name=$(python -c "from wheel.pep425tags import get_platform; print(get_platform().replace('linux', 'manylinux1'))")
    EOF
  - cat setup.cfg
  - make wheel

deploy:
  provider: pypi
  user: mastak
  password: $PYPI_PASSWORD
#  password:
#    secure: HMfD4NXKXouM8JE69urN4ZLNiF5y2ieVXzedECvAbdmR4cSuyJnVljBEEq5ykn3xNexauigvY/gtestRKhG4BRzIaLOE5Ihz0eRqky0HO1c90zDVxcCrsjGOW1oX2X5odDgpZ+plWyTHUW1G5lIyK8fF9WLBUsvYQ6r9EPCjSH9y3R4ddDuddXZQuRuN/HxNyPhJWAJYeeVT25Cngbkvht+3UGPq4Dy9owZ/tilcptBRpOeS3HL4phPwtOuiz8ezmJjmHMjVKG9JeWK31i89uPqvmRGskU6Or+zh3y9Qwnw60Fa+ahDk2xgV94T9FAmbIuWm2CiIdpRSPpaW9FsvbyTk9DXr04dM/xY/vzN/NhGDP6N/ZJbW9zmQ7gaoLhMi60b8FyZrqWATToW3Hj4bngJceee6mOOKgBNmVDc5sdxQMlc2pIdpc9YBJHYJlJ0Wgb5KjqUnrPNIQbTpwkXrkas7qpwh40PbUcokGmqTsjY0Bt2S37GULXqgshZhYar1s8ZAxoIEhdt6FqXOuqXKa/5DiuUd3W+c1advmB/62k6gkB39QQF5a27ozYrRua+hqcRt6X5qEf4oDbSOK6YW8EioSgzvbKSzDd5SqF2Vu2oWL1AB2RyC+suG5DMH5QD+u1bSmQoUMQLjUSRxcnVOpTELUTpKUHHGsGV27coLvgE=
  distributions: bdist_wheel
  skip_cleanup: true
  skip_existing: true
  on:
    branch: master
